use_frameworks!

platform :ios, '8.0'

target 'LCActionSheet_Example' do
  pod 'LCActionSheet', :path => '../'

  pod 'Reveal-SDK', :configurations => ['Debug']

  target 'LCActionSheet_Tests' do
    inherit! :search_paths

    
  end
end
