# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'

target 'LCActionSheetDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for LCActionSheetDemo
  pod 'LCActionSheet', :path => '../'
  
  # pod 'Masonry'
  # pod 'LCBlur'
  # pod 'GPUImage', '~> 0.1.7'

end
