platform :ios, '8.0'

target 'LCActionSheetDemo' do
  # use_frameworks!

  # Pods for LCActionSheetDemo
  pod 'LCActionSheet', :path => '../'
  
  pod 'Reveal-SDK', :configurations => ['Debug']
  # pod 'JGProgressHUD'
  
  # pod 'Masonry'
  # pod 'LCBlur'
  # pod 'GPUImage', '~> 0.1.7'

end
